# config/meta.yml

meta_product_name: "Chronos Laytime"
meta_title: "Chronos Laytime - Fully-automated laytime management system"
meta_description: "Chronos-laytime is a fully automated laytime management tool. By using coded translations of charter party clauses, the app gives the user access to real-time demurrage calculations, valuable KPI's and data analysis while thremendously reducing work-load and risk of human-error. This accomodates cost-reduction, faster invoicing, identification of toxic clauses and improves commercial decision making. Contact us for more information."
meta_type: "CHAR"
meta_url: "https://chronos-laytime.herokuapp.com"
meta_image: "liquid_bulk_terminal.jpeg"
